/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formes;

/**
 *
 * @author nikos
 */
public class AnazitisiVivliouInternalFrame extends javax.swing.JInternalFrame {

    /**
     * Creates new form AnazitisiVivliouInternalFrame
     */
    public AnazitisiVivliouInternalFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        searchPane = new javax.swing.JPanel();
        anazitisiMeLbl = new javax.swing.JLabel();
        isbnRadioBtn = new javax.swing.JRadioButton();
        titloVivliouRadioBtn = new javax.swing.JRadioButton();
        dwsePliroforiaLbl = new javax.swing.JLabel();
        pliroforiaFld = new javax.swing.JTextField();
        anazitisiBtn = new javax.swing.JButton();
        katharismosPediwnBtn = new javax.swing.JButton();
        kleisimoParathirouBtn = new javax.swing.JButton();
        bookInfoPane = new javax.swing.JPanel();
        isbnLbl = new javax.swing.JLabel();
        titlosVivliouLbl = new javax.swing.JLabel();
        ekdoseisVivliouLbl = new javax.swing.JLabel();
        siggrafeasLbl = new javax.swing.JLabel();
        scrollerSiggrafeisList = new javax.swing.JScrollPane();
        siggrafeisList = new javax.swing.JList();
        ekdoseisVivliouFld = new javax.swing.JTextField();
        titlosVivliouFld = new javax.swing.JTextField();
        isbnFld = new javax.swing.JTextField();
        perigrafiVivliouLbl = new javax.swing.JLabel();
        scrollerPerigrafiVivliouTxtPane = new javax.swing.JScrollPane();
        perigrafiVivliouTxtPane = new javax.swing.JTextPane();
        bookCoverIconPane = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        lblToLoadBookCoverIcon = new javax.swing.JLabel();
        fortwseExwfylloVivliouBtn = new javax.swing.JButton();
        actionsPane = new javax.swing.JPanel();
        enimerwsiVivliouBtn = new javax.swing.JButton();
        akirwsiEnimerwsisBtn = new javax.swing.JButton();
        epivevaiwshEnimerwsisBtn = new javax.swing.JButton();
        diagrafiVivliouBtn = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Αναζήτηση Βιβλίου");

        searchPane.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Search", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Bitstream Charter", 0, 14), java.awt.Color.black)); // NOI18N

        anazitisiMeLbl.setText("Αναζήτηση με:");

        isbnRadioBtn.setText("ISBN");

        titloVivliouRadioBtn.setText("Τίτλος βιβλίου");

        dwsePliroforiaLbl.setText("Δώσε πληροφορία:");

        anazitisiBtn.setText("Αναζήτηση");

        katharismosPediwnBtn.setText("Καθαρισμός πεδίων");

        kleisimoParathirouBtn.setText("Κλείσιμο παράθυρου");

        javax.swing.GroupLayout searchPaneLayout = new javax.swing.GroupLayout(searchPane);
        searchPane.setLayout(searchPaneLayout);
        searchPaneLayout.setHorizontalGroup(
            searchPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(searchPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(searchPaneLayout.createSequentialGroup()
                        .addComponent(dwsePliroforiaLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pliroforiaFld))
                    .addGroup(searchPaneLayout.createSequentialGroup()
                        .addGroup(searchPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(searchPaneLayout.createSequentialGroup()
                                .addComponent(anazitisiMeLbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(isbnRadioBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(titloVivliouRadioBtn))
                            .addGroup(searchPaneLayout.createSequentialGroup()
                                .addComponent(anazitisiBtn)
                                .addGap(18, 18, 18)
                                .addComponent(katharismosPediwnBtn)
                                .addGap(18, 18, 18)
                                .addComponent(kleisimoParathirouBtn)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        searchPaneLayout.setVerticalGroup(
            searchPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(searchPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(anazitisiMeLbl)
                    .addComponent(isbnRadioBtn)
                    .addComponent(titloVivliouRadioBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(searchPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dwsePliroforiaLbl)
                    .addComponent(pliroforiaFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(searchPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(anazitisiBtn)
                    .addComponent(katharismosPediwnBtn)
                    .addComponent(kleisimoParathirouBtn))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        bookInfoPane.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Book's Info", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Bitstream Charter", 0, 14), java.awt.Color.black)); // NOI18N

        isbnLbl.setText("ISBN:");

        titlosVivliouLbl.setText("Τίτλος Βιβλίου:");

        ekdoseisVivliouLbl.setText("Εκδόσεις βιβλίου:");

        siggrafeasLbl.setText("Συγγραφέας/Συγγραφείς βιβλίου:");

        scrollerSiggrafeisList.setViewportView(siggrafeisList);

        ekdoseisVivliouFld.setEditable(false);

        titlosVivliouFld.setEditable(false);

        isbnFld.setEditable(false);

        perigrafiVivliouLbl.setText("Περιγραφή βιβλίου:");

        perigrafiVivliouTxtPane.setEditable(false);
        scrollerPerigrafiVivliouTxtPane.setViewportView(perigrafiVivliouTxtPane);

        javax.swing.GroupLayout bookInfoPaneLayout = new javax.swing.GroupLayout(bookInfoPane);
        bookInfoPane.setLayout(bookInfoPaneLayout);
        bookInfoPaneLayout.setHorizontalGroup(
            bookInfoPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bookInfoPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bookInfoPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(scrollerPerigrafiVivliouTxtPane)
                    .addGroup(bookInfoPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(bookInfoPaneLayout.createSequentialGroup()
                            .addGroup(bookInfoPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(siggrafeasLbl)
                                .addComponent(ekdoseisVivliouLbl)
                                .addComponent(titlosVivliouLbl)
                                .addComponent(isbnLbl))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(bookInfoPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(isbnFld)
                                .addComponent(titlosVivliouFld)
                                .addComponent(ekdoseisVivliouFld)
                                .addComponent(scrollerSiggrafeisList, javax.swing.GroupLayout.DEFAULT_SIZE, 311, Short.MAX_VALUE)))
                        .addComponent(perigrafiVivliouLbl)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        bookInfoPaneLayout.setVerticalGroup(
            bookInfoPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bookInfoPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bookInfoPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(isbnLbl)
                    .addComponent(isbnFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(bookInfoPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titlosVivliouLbl)
                    .addComponent(titlosVivliouFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(bookInfoPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ekdoseisVivliouLbl)
                    .addComponent(ekdoseisVivliouFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(bookInfoPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(siggrafeasLbl)
                    .addComponent(scrollerSiggrafeisList, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(perigrafiVivliouLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollerPerigrafiVivliouTxtPane, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                .addContainerGap())
        );

        bookCoverIconPane.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Book's Cover Icon", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Bitstream Charter", 0, 14), java.awt.Color.black)); // NOI18N

        jLabel7.setText("Εξώφυλλο βιβλίου:");

        lblToLoadBookCoverIcon.setText("εδώ φορτώνεται η εικόνα...");

        fortwseExwfylloVivliouBtn.setText("Φόρτωσε εξώφυλλο");
        fortwseExwfylloVivliouBtn.setEnabled(false);

        javax.swing.GroupLayout bookCoverIconPaneLayout = new javax.swing.GroupLayout(bookCoverIconPane);
        bookCoverIconPane.setLayout(bookCoverIconPaneLayout);
        bookCoverIconPaneLayout.setHorizontalGroup(
            bookCoverIconPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bookCoverIconPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bookCoverIconPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bookCoverIconPaneLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(fortwseExwfylloVivliouBtn))
                    .addComponent(lblToLoadBookCoverIcon))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        bookCoverIconPaneLayout.setVerticalGroup(
            bookCoverIconPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bookCoverIconPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bookCoverIconPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(fortwseExwfylloVivliouBtn))
                .addGap(18, 18, 18)
                .addComponent(lblToLoadBookCoverIcon)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        actionsPane.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Actions", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Bitstream Charter", 0, 14), java.awt.Color.black)); // NOI18N

        enimerwsiVivliouBtn.setText("Ενημέρωση Βιβλίου");
        enimerwsiVivliouBtn.setEnabled(false);

        akirwsiEnimerwsisBtn.setText("Ακύρωση Ενημέρωσης");
        akirwsiEnimerwsisBtn.setEnabled(false);

        epivevaiwshEnimerwsisBtn.setText("Επιβεβαίωση Ενημέρωσης");
        epivevaiwshEnimerwsisBtn.setEnabled(false);

        diagrafiVivliouBtn.setText("Διαγραφή Βιβλίου");
        diagrafiVivliouBtn.setEnabled(false);

        javax.swing.GroupLayout actionsPaneLayout = new javax.swing.GroupLayout(actionsPane);
        actionsPane.setLayout(actionsPaneLayout);
        actionsPaneLayout.setHorizontalGroup(
            actionsPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(actionsPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(actionsPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(actionsPaneLayout.createSequentialGroup()
                        .addComponent(enimerwsiVivliouBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(akirwsiEnimerwsisBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(epivevaiwshEnimerwsisBtn))
                    .addComponent(diagrafiVivliouBtn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        actionsPaneLayout.setVerticalGroup(
            actionsPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(actionsPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(actionsPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enimerwsiVivliouBtn)
                    .addComponent(akirwsiEnimerwsisBtn)
                    .addComponent(epivevaiwshEnimerwsisBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(diagrafiVivliouBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(searchPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bookInfoPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bookCoverIconPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(actionsPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(searchPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bookInfoPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(actionsPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bookCoverIconPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel actionsPane;
    private javax.swing.JButton akirwsiEnimerwsisBtn;
    private javax.swing.JButton anazitisiBtn;
    private javax.swing.JLabel anazitisiMeLbl;
    private javax.swing.JPanel bookCoverIconPane;
    private javax.swing.JPanel bookInfoPane;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton diagrafiVivliouBtn;
    private javax.swing.JLabel dwsePliroforiaLbl;
    private javax.swing.JTextField ekdoseisVivliouFld;
    private javax.swing.JLabel ekdoseisVivliouLbl;
    private javax.swing.JButton enimerwsiVivliouBtn;
    private javax.swing.JButton epivevaiwshEnimerwsisBtn;
    private javax.swing.JButton fortwseExwfylloVivliouBtn;
    private javax.swing.JTextField isbnFld;
    private javax.swing.JLabel isbnLbl;
    private javax.swing.JRadioButton isbnRadioBtn;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JButton katharismosPediwnBtn;
    private javax.swing.JButton kleisimoParathirouBtn;
    private javax.swing.JLabel lblToLoadBookCoverIcon;
    private javax.swing.JLabel perigrafiVivliouLbl;
    private javax.swing.JTextPane perigrafiVivliouTxtPane;
    private javax.swing.JTextField pliroforiaFld;
    private javax.swing.JScrollPane scrollerPerigrafiVivliouTxtPane;
    private javax.swing.JScrollPane scrollerSiggrafeisList;
    private javax.swing.JPanel searchPane;
    private javax.swing.JLabel siggrafeasLbl;
    private javax.swing.JList siggrafeisList;
    private javax.swing.JRadioButton titloVivliouRadioBtn;
    private javax.swing.JTextField titlosVivliouFld;
    private javax.swing.JLabel titlosVivliouLbl;
    // End of variables declaration//GEN-END:variables
}
