/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formes;

import database.connection.DbConnection;
import database.daos.MelhDAO;
import database.models.Melos;
import javax.swing.JOptionPane;

/**
 *
 * @author nikos
 */
public class AnazitisiMelousInternalFrame extends javax.swing.JInternalFrame {

    private MelhDAO melhDAO = new MelhDAO(DbConnection.getInstance().getConnection());

    /**
     * Creates new form AnazitisiMelousInternalFrame
     */
    public AnazitisiMelousInternalFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        radioButtonGroupForSearch = new javax.swing.ButtonGroup();
        mainPane = new javax.swing.JPanel();
        searchResultPane = new javax.swing.JPanel();
        arithmosMitrwouMelousLbl = new javax.swing.JLabel();
        onomaMelousLbl = new javax.swing.JLabel();
        epithetoMelousLbl = new javax.swing.JLabel();
        emailMelousLbl = new javax.swing.JLabel();
        kwdikosMelousLbl = new javax.swing.JLabel();
        arithmosMitrwouFld = new javax.swing.JTextField();
        onomaFld = new javax.swing.JTextField();
        emailFld = new javax.swing.JTextField();
        epithetoFld = new javax.swing.JTextField();
        kwdikosFld = new javax.swing.JTextField();
        kleisimoDialogBtn = new javax.swing.JButton();
        searchPane = new javax.swing.JPanel();
        anazitisiMeLbl = new javax.swing.JLabel();
        arithmoMitrwouRadioBtn = new javax.swing.JRadioButton();
        epithetoMelousRadioBtn = new javax.swing.JRadioButton();
        dwsePliroforiaLbl = new javax.swing.JLabel();
        pliroforiaFld = new javax.swing.JTextField();
        anazitisiBtn = new javax.swing.JButton();
        katharismosPediwnBtn = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Αναζήτηση Μέλους");

        searchResultPane.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Search Result", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Bitstream Charter", 0, 14), java.awt.Color.black)); // NOI18N

        arithmosMitrwouMelousLbl.setText("Αριθμός Μητρώου μέλους:");

        onomaMelousLbl.setText("Όνομα μέλους:");

        epithetoMelousLbl.setText("Επίθετο μέλους:");

        emailMelousLbl.setText("Email μέλους:");

        kwdikosMelousLbl.setText("Κωδικός μέλους (password):");

        arithmosMitrwouFld.setEditable(false);

        onomaFld.setEditable(false);

        emailFld.setEditable(false);

        epithetoFld.setEditable(false);

        kwdikosFld.setEditable(false);

        kleisimoDialogBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui_icons/close.png"))); // NOI18N
        kleisimoDialogBtn.setText("Κλείσιμο παράθυρου");
        kleisimoDialogBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kleisimoDialogBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout searchResultPaneLayout = new javax.swing.GroupLayout(searchResultPane);
        searchResultPane.setLayout(searchResultPaneLayout);
        searchResultPaneLayout.setHorizontalGroup(
            searchResultPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchResultPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(searchResultPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(searchResultPaneLayout.createSequentialGroup()
                        .addGroup(searchResultPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(arithmosMitrwouMelousLbl)
                            .addComponent(onomaMelousLbl)
                            .addComponent(epithetoMelousLbl)
                            .addComponent(emailMelousLbl)
                            .addComponent(kwdikosMelousLbl))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(searchResultPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(arithmosMitrwouFld)
                            .addComponent(onomaFld)
                            .addComponent(emailFld)
                            .addComponent(epithetoFld)
                            .addComponent(kwdikosFld)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, searchResultPaneLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(kleisimoDialogBtn)))
                .addContainerGap())
        );
        searchResultPaneLayout.setVerticalGroup(
            searchResultPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchResultPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(searchResultPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(arithmosMitrwouMelousLbl)
                    .addComponent(arithmosMitrwouFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(searchResultPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(onomaMelousLbl)
                    .addComponent(onomaFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(searchResultPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(epithetoMelousLbl)
                    .addComponent(epithetoFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(searchResultPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailMelousLbl)
                    .addComponent(emailFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(searchResultPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kwdikosMelousLbl)
                    .addComponent(kwdikosFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(kleisimoDialogBtn)
                .addContainerGap())
        );

        searchPane.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Search Member", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Bitstream Charter", 0, 14), java.awt.Color.black)); // NOI18N

        anazitisiMeLbl.setText("Αναζήτηση με:");

        radioButtonGroupForSearch.add(arithmoMitrwouRadioBtn);
        arithmoMitrwouRadioBtn.setText("Αριθμό μητρώου");

        radioButtonGroupForSearch.add(epithetoMelousRadioBtn);
        epithetoMelousRadioBtn.setText("Επίθετο Μέλους");

        dwsePliroforiaLbl.setText("Δώσε πληροφορία:");

        anazitisiBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui_icons/search.png"))); // NOI18N
        anazitisiBtn.setText("Αναζήτηση!");
        anazitisiBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anazitisiBtnActionPerformed(evt);
            }
        });

        katharismosPediwnBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui_icons/discardChanges.png"))); // NOI18N
        katharismosPediwnBtn.setText("Καθαρισμός πεδίων");
        katharismosPediwnBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                katharismosPediwnBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout searchPaneLayout = new javax.swing.GroupLayout(searchPane);
        searchPane.setLayout(searchPaneLayout);
        searchPaneLayout.setHorizontalGroup(
            searchPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(searchPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(searchPaneLayout.createSequentialGroup()
                        .addComponent(anazitisiMeLbl)
                        .addGap(18, 18, 18)
                        .addComponent(arithmoMitrwouRadioBtn)
                        .addGap(18, 18, 18)
                        .addComponent(epithetoMelousRadioBtn))
                    .addGroup(searchPaneLayout.createSequentialGroup()
                        .addComponent(dwsePliroforiaLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pliroforiaFld, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(anazitisiBtn)
                        .addGap(18, 18, 18)
                        .addComponent(katharismosPediwnBtn)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        searchPaneLayout.setVerticalGroup(
            searchPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(searchPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(anazitisiMeLbl)
                    .addComponent(arithmoMitrwouRadioBtn)
                    .addComponent(epithetoMelousRadioBtn))
                .addGap(18, 18, 18)
                .addGroup(searchPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dwsePliroforiaLbl)
                    .addComponent(pliroforiaFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(anazitisiBtn)
                    .addComponent(katharismosPediwnBtn))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout mainPaneLayout = new javax.swing.GroupLayout(mainPane);
        mainPane.setLayout(mainPaneLayout);
        mainPaneLayout.setHorizontalGroup(
            mainPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(searchPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(searchResultPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        mainPaneLayout.setVerticalGroup(
            mainPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(searchPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(searchResultPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void katharismosPediwnBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_katharismosPediwnBtnActionPerformed

        arithmosMitrwouFld.setText("");
        emailFld.setText("");
        epithetoFld.setText("");
        kwdikosFld.setText("");
        onomaFld.setText("");
        pliroforiaFld.setText("");

    }//GEN-LAST:event_katharismosPediwnBtnActionPerformed

    private void kleisimoDialogBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kleisimoDialogBtnActionPerformed
        this.dispose();
    }//GEN-LAST:event_kleisimoDialogBtnActionPerformed

    private void anazitisiBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anazitisiBtnActionPerformed

        if (arithmoMitrwouRadioBtn.isSelected()) {

            String input = pliroforiaFld.getText();
            if (input.trim().equals("")) {
                JOptionPane.showMessageDialog(this, "Παρακαλώ δώσε έγκυρο ΑΜ!");
                return;
            }

            try {
                Integer.parseInt(input);
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(this, "Ο αριθμός μητρώου αποτελείται μονο απο αριθμούς!");
                return;
            }

            Melos res = melhDAO.searchMelosByAm(Integer.parseInt(input));
            if (res == null) {

                JOptionPane.showMessageDialog(this, "Δεν υπάρχει μέλος με αυτο το ΑΜ!");

                arithmosMitrwouFld.setText("");
                emailFld.setText("");
                epithetoFld.setText("");
                kwdikosFld.setText("");
                onomaFld.setText("");
                pliroforiaFld.setText("");

            } else {

                arithmosMitrwouFld.setText(res.getAm() + "");
                emailFld.setText(res.getEmail());
                epithetoFld.setText(res.getEpitheto());
                kwdikosFld.setText(res.getPass());
                onomaFld.setText(res.getOnoma());

            }

        } else if (epithetoMelousRadioBtn.isSelected()) {

            String input = pliroforiaFld.getText();
            if (input.trim().equals("")) {
                JOptionPane.showMessageDialog(this, "Παρακαλώ δώσε έγκυρο επίθετο!");
                return;
            }
            
            
            Melos res = melhDAO.searchMelosByEpitheto(input);
            if (res == null) {

                JOptionPane.showMessageDialog(this, "Δεν υπάρχει μέλος με αυτο το επίθετο!");

                arithmosMitrwouFld.setText("");
                emailFld.setText("");
                epithetoFld.setText("");
                kwdikosFld.setText("");
                onomaFld.setText("");
                pliroforiaFld.setText("");

            } else {

                arithmosMitrwouFld.setText(res.getAm() + "");
                emailFld.setText(res.getEmail());
                epithetoFld.setText(res.getEpitheto());
                kwdikosFld.setText(res.getPass());
                onomaFld.setText(res.getOnoma());

            }


        } else {
            JOptionPane.showMessageDialog(this, "Παρακαλώ επέλεξε ενα κριτήριο αναζήτησης!");
        }


    }//GEN-LAST:event_anazitisiBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton anazitisiBtn;
    private javax.swing.JLabel anazitisiMeLbl;
    private javax.swing.JRadioButton arithmoMitrwouRadioBtn;
    private javax.swing.JTextField arithmosMitrwouFld;
    private javax.swing.JLabel arithmosMitrwouMelousLbl;
    private javax.swing.JLabel dwsePliroforiaLbl;
    private javax.swing.JTextField emailFld;
    private javax.swing.JLabel emailMelousLbl;
    private javax.swing.JTextField epithetoFld;
    private javax.swing.JLabel epithetoMelousLbl;
    private javax.swing.JRadioButton epithetoMelousRadioBtn;
    private javax.swing.JButton katharismosPediwnBtn;
    private javax.swing.JButton kleisimoDialogBtn;
    private javax.swing.JTextField kwdikosFld;
    private javax.swing.JLabel kwdikosMelousLbl;
    private javax.swing.JPanel mainPane;
    private javax.swing.JTextField onomaFld;
    private javax.swing.JLabel onomaMelousLbl;
    private javax.swing.JTextField pliroforiaFld;
    private javax.swing.ButtonGroup radioButtonGroupForSearch;
    private javax.swing.JPanel searchPane;
    private javax.swing.JPanel searchResultPane;
    // End of variables declaration//GEN-END:variables
}
