/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formes;

/**
 *
 * @author nikos
 */
public class DiaxeirisiAntitypwnVivliouInternalFrame extends javax.swing.JInternalFrame {

    /**
     * Creates new form DiaxeirisiAntitypwnVivliwnInternalFrame
     */
    public DiaxeirisiAntitypwnVivliouInternalFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        searchPane = new javax.swing.JPanel();
        isbnLbl = new javax.swing.JLabel();
        isbnFld = new javax.swing.JTextField();
        anazitisiBtn = new javax.swing.JButton();
        katahrismosPediwnBtn = new javax.swing.JButton();
        scrollerForAntitypa = new javax.swing.JScrollPane();
        antitypaTable = new javax.swing.JTable();
        utilsPane = new javax.swing.JPanel();
        deletePane = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        insertBookCopyPane = new javax.swing.JPanel();
        katastasiLbl = new javax.swing.JLabel();
        katastasiComboBox = new javax.swing.JComboBox();
        eisagwgiAntitypouBtn = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Διαχείριση αντίτυπων βιβλίου");

        searchPane.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Search Book's Copies", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Bitstream Charter", 0, 14), java.awt.Color.black)); // NOI18N

        isbnLbl.setText("Δώσε ISBN:");

        anazitisiBtn.setText("Αναζήτηση");

        katahrismosPediwnBtn.setText("Καθαρισμός πεδίων");

        javax.swing.GroupLayout searchPaneLayout = new javax.swing.GroupLayout(searchPane);
        searchPane.setLayout(searchPaneLayout);
        searchPaneLayout.setHorizontalGroup(
            searchPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(searchPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(searchPaneLayout.createSequentialGroup()
                        .addComponent(isbnLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(isbnFld, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(searchPaneLayout.createSequentialGroup()
                        .addComponent(anazitisiBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(katahrismosPediwnBtn)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        searchPaneLayout.setVerticalGroup(
            searchPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(searchPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(isbnLbl)
                    .addComponent(isbnFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(searchPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(anazitisiBtn)
                    .addComponent(katahrismosPediwnBtn))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        antitypaTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scrollerForAntitypa.setViewportView(antitypaTable);

        utilsPane.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Selected Book Copy Actions", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Bitstream Charter", 0, 14), java.awt.Color.black)); // NOI18N

        deletePane.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Delete Book Copy", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Bitstream Charter", 0, 14), java.awt.Color.black)); // NOI18N

        jButton3.setText("Διαγραφή Αντίτυπου");
        jButton3.setEnabled(false);

        javax.swing.GroupLayout deletePaneLayout = new javax.swing.GroupLayout(deletePane);
        deletePane.setLayout(deletePaneLayout);
        deletePaneLayout.setHorizontalGroup(
            deletePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deletePaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        deletePaneLayout.setVerticalGroup(
            deletePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deletePaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        insertBookCopyPane.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Insert New Book Copy", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Bitstream Charter", 0, 14), java.awt.Color.black)); // NOI18N

        katastasiLbl.setText("Επίλεξε κατάσταση αντίτυπου:");

        katastasiComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Κακιά", "Μέτρια", "Καλή", "Άριστη" }));

        eisagwgiAntitypouBtn.setText("Εισαγωγή αντίτυπου");
        eisagwgiAntitypouBtn.setToolTipText("");
        eisagwgiAntitypouBtn.setEnabled(false);

        javax.swing.GroupLayout insertBookCopyPaneLayout = new javax.swing.GroupLayout(insertBookCopyPane);
        insertBookCopyPane.setLayout(insertBookCopyPaneLayout);
        insertBookCopyPaneLayout.setHorizontalGroup(
            insertBookCopyPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(insertBookCopyPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(insertBookCopyPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(katastasiLbl)
                    .addComponent(katastasiComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eisagwgiAntitypouBtn))
                .addContainerGap(115, Short.MAX_VALUE))
        );
        insertBookCopyPaneLayout.setVerticalGroup(
            insertBookCopyPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(insertBookCopyPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(katastasiLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(katastasiComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(eisagwgiAntitypouBtn)
                .addContainerGap(236, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout utilsPaneLayout = new javax.swing.GroupLayout(utilsPane);
        utilsPane.setLayout(utilsPaneLayout);
        utilsPaneLayout.setHorizontalGroup(
            utilsPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(utilsPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(utilsPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(deletePane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(insertBookCopyPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        utilsPaneLayout.setVerticalGroup(
            utilsPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(utilsPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(deletePane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(insertBookCopyPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(scrollerForAntitypa, javax.swing.GroupLayout.DEFAULT_SIZE, 526, Short.MAX_VALUE)
                    .addComponent(searchPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(utilsPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(utilsPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(searchPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(scrollerForAntitypa, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton anazitisiBtn;
    private javax.swing.JTable antitypaTable;
    private javax.swing.JPanel deletePane;
    private javax.swing.JButton eisagwgiAntitypouBtn;
    private javax.swing.JPanel insertBookCopyPane;
    private javax.swing.JTextField isbnFld;
    private javax.swing.JLabel isbnLbl;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton katahrismosPediwnBtn;
    private javax.swing.JComboBox katastasiComboBox;
    private javax.swing.JLabel katastasiLbl;
    private javax.swing.JScrollPane scrollerForAntitypa;
    private javax.swing.JPanel searchPane;
    private javax.swing.JPanel utilsPane;
    // End of variables declaration//GEN-END:variables
}
