package formes;

/**
 *
 * @author nikos
 */
public class EisagwgiNeouSiggrafeaInternalFrame extends javax.swing.JInternalFrame {

    /**
     * Creates new form EisagwgiNeouSiggrafeaInternalFrame
     */
    public EisagwgiNeouSiggrafeaInternalFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPane = new javax.swing.JPanel();
        onomaSiggrafeaLbl = new javax.swing.JLabel();
        epithetoSiggrafeaLbl = new javax.swing.JLabel();
        onomaSiggrafeaFld = new javax.swing.JTextField();
        epithetoSiggrafeaFld = new javax.swing.JTextField();
        kleisimoParathirouBtn = new javax.swing.JButton();
        eisagwgiNeouSiggrafeaBtn = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Εισαγωγή νέου συγγραφέα");

        onomaSiggrafeaLbl.setText("Όνομα συγγραφέα:");

        epithetoSiggrafeaLbl.setText("Επίθετο συγγραφέα:");

        kleisimoParathirouBtn.setText("Κλείσιμο Παράθυρου");

        eisagwgiNeouSiggrafeaBtn.setText("Εισαγωγή νεου συγγραφέα");

        javax.swing.GroupLayout mainPaneLayout = new javax.swing.GroupLayout(mainPane);
        mainPane.setLayout(mainPaneLayout);
        mainPaneLayout.setHorizontalGroup(
            mainPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(epithetoSiggrafeaLbl)
                    .addComponent(onomaSiggrafeaLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(mainPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(onomaSiggrafeaFld, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                    .addComponent(epithetoSiggrafeaFld))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPaneLayout.createSequentialGroup()
                .addContainerGap(73, Short.MAX_VALUE)
                .addComponent(eisagwgiNeouSiggrafeaBtn)
                .addGap(18, 18, 18)
                .addComponent(kleisimoParathirouBtn)
                .addContainerGap())
        );
        mainPaneLayout.setVerticalGroup(
            mainPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(onomaSiggrafeaLbl)
                    .addComponent(onomaSiggrafeaFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(mainPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(epithetoSiggrafeaLbl)
                    .addComponent(epithetoSiggrafeaFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addGroup(mainPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kleisimoParathirouBtn)
                    .addComponent(eisagwgiNeouSiggrafeaBtn))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(mainPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton eisagwgiNeouSiggrafeaBtn;
    private javax.swing.JTextField epithetoSiggrafeaFld;
    private javax.swing.JLabel epithetoSiggrafeaLbl;
    private javax.swing.JButton kleisimoParathirouBtn;
    private javax.swing.JPanel mainPane;
    private javax.swing.JTextField onomaSiggrafeaFld;
    private javax.swing.JLabel onomaSiggrafeaLbl;
    // End of variables declaration//GEN-END:variables
}
