/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package formes;

/**
 *
 * @author nikos
 */
public class EmfanisiDaneismenwnAntitypwnVivliwnMelous extends javax.swing.JInternalFrame {

    /**
     * Creates new form EmfanisiDaneismenwnAntitypwnVivliwnMelous
     */
    public EmfanisiDaneismenwnAntitypwnVivliwnMelous() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        firstPane = new javax.swing.JPanel();
        amMelousLbl = new javax.swing.JLabel();
        amMelousFld = new javax.swing.JTextField();
        anazitisiDaneismenwnAntitypwnBtn = new javax.swing.JButton();
        kleisimoParathirouBtn = new javax.swing.JButton();
        secondPane = new javax.swing.JPanel();
        isbnAntitypoyVivliouLbl = new javax.swing.JLabel();
        auxwnArithmosAntitypouLbl = new javax.swing.JLabel();
        katastasiAntitypouLbl = new javax.swing.JLabel();
        isbnAntitypouVivliouFld = new javax.swing.JTextField();
        auxwnArithmosAntitypouFld = new javax.swing.JTextField();
        katastasiAntitypouFld = new javax.swing.JTextField();
        epistrofiAntitypouBtn = new javax.swing.JButton();
        scrollPane = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Εμφάνιση δανεισμένων αντιτύπων βιβλίων μέλους");

        amMelousLbl.setText("Δώσε αριθμό μητρώου μέλους:");

        anazitisiDaneismenwnAntitypwnBtn.setText("Αναζήτηση δανεισμένων αντιτύπων");
        anazitisiDaneismenwnAntitypwnBtn.setToolTipText("");

        kleisimoParathirouBtn.setText("Κλείσιμο παράθυρου");

        javax.swing.GroupLayout firstPaneLayout = new javax.swing.GroupLayout(firstPane);
        firstPane.setLayout(firstPaneLayout);
        firstPaneLayout.setHorizontalGroup(
            firstPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(firstPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(firstPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(firstPaneLayout.createSequentialGroup()
                        .addComponent(amMelousLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(amMelousFld, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(anazitisiDaneismenwnAntitypwnBtn)
                    .addComponent(kleisimoParathirouBtn))
                .addContainerGap(75, Short.MAX_VALUE))
        );

        firstPaneLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {anazitisiDaneismenwnAntitypwnBtn, kleisimoParathirouBtn});

        firstPaneLayout.setVerticalGroup(
            firstPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(firstPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(firstPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(amMelousLbl)
                    .addComponent(amMelousFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(anazitisiDaneismenwnAntitypwnBtn)
                .addGap(18, 18, 18)
                .addComponent(kleisimoParathirouBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        firstPaneLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {anazitisiDaneismenwnAntitypwnBtn, kleisimoParathirouBtn});

        isbnAntitypoyVivliouLbl.setText("ISBN αντίτυπου βιβλίου:");

        auxwnArithmosAntitypouLbl.setText("Αύξων αριθμός αντίτυπου:");

        katastasiAntitypouLbl.setText("Κατάσταση αντίτυπου:");

        isbnAntitypouVivliouFld.setEditable(false);

        auxwnArithmosAntitypouFld.setEditable(false);

        katastasiAntitypouFld.setEditable(false);

        epistrofiAntitypouBtn.setText("Επιστροφή αντίτυπου");
        epistrofiAntitypouBtn.setEnabled(false);

        javax.swing.GroupLayout secondPaneLayout = new javax.swing.GroupLayout(secondPane);
        secondPane.setLayout(secondPaneLayout);
        secondPaneLayout.setHorizontalGroup(
            secondPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(secondPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(secondPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(epistrofiAntitypouBtn)
                    .addGroup(secondPaneLayout.createSequentialGroup()
                        .addGroup(secondPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(auxwnArithmosAntitypouLbl)
                            .addComponent(isbnAntitypoyVivliouLbl)
                            .addComponent(katastasiAntitypouLbl))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(secondPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(katastasiAntitypouFld, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                            .addComponent(auxwnArithmosAntitypouFld)
                            .addComponent(isbnAntitypouVivliouFld))))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        secondPaneLayout.setVerticalGroup(
            secondPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(secondPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(secondPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(isbnAntitypoyVivliouLbl)
                    .addComponent(isbnAntitypouVivliouFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(secondPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(auxwnArithmosAntitypouLbl)
                    .addComponent(auxwnArithmosAntitypouFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(secondPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(katastasiAntitypouLbl)
                    .addComponent(katastasiAntitypouFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(epistrofiAntitypouBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scrollPane.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollPane)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(firstPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(secondPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(secondPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(firstPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(scrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField amMelousFld;
    private javax.swing.JLabel amMelousLbl;
    private javax.swing.JButton anazitisiDaneismenwnAntitypwnBtn;
    private javax.swing.JTextField auxwnArithmosAntitypouFld;
    private javax.swing.JLabel auxwnArithmosAntitypouLbl;
    private javax.swing.JButton epistrofiAntitypouBtn;
    private javax.swing.JPanel firstPane;
    private javax.swing.JTextField isbnAntitypouVivliouFld;
    private javax.swing.JLabel isbnAntitypoyVivliouLbl;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField katastasiAntitypouFld;
    private javax.swing.JLabel katastasiAntitypouLbl;
    private javax.swing.JButton kleisimoParathirouBtn;
    private javax.swing.JScrollPane scrollPane;
    private javax.swing.JPanel secondPane;
    // End of variables declaration//GEN-END:variables
}
