/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package formes;

/**
 *
 * @author nikos
 */
public class EmfanisiVivliwnInternalFrame extends javax.swing.JInternalFrame {

    /**
     * Creates new form EmfanisiVivliwnInternalFrame
     */
    public EmfanisiVivliwnInternalFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollerBooksTable = new javax.swing.JScrollPane();
        booksTable = new javax.swing.JTable();
        firstPane = new javax.swing.JPanel();
        isbnLbl = new javax.swing.JLabel();
        titleLbl = new javax.swing.JLabel();
        ekdoseisLbl = new javax.swing.JLabel();
        kleisimoParathirouBtn = new javax.swing.JButton();
        ekdoseisFld = new javax.swing.JTextField();
        titleFld = new javax.swing.JTextField();
        isbnFld = new javax.swing.JTextField();
        siggrafeasLbl = new javax.swing.JLabel();
        scrollerSiggrafeisList = new javax.swing.JScrollPane();
        siggrafeisList = new javax.swing.JList();
        perigrafiLbl = new javax.swing.JLabel();
        scrollerPerigrafiTxtPane = new javax.swing.JScrollPane();
        perigrafiTxtPane = new javax.swing.JTextPane();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Εμφάνιση Βιβλίων");

        booksTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scrollerBooksTable.setViewportView(booksTable);

        isbnLbl.setText("ISBN βιβλίου:");

        titleLbl.setText("Τίτλος βιβλίου:");

        ekdoseisLbl.setText("Εκδόσεις βιβλίου:");

        kleisimoParathirouBtn.setText("Κλείσιμο παράθυρου");

        ekdoseisFld.setEditable(false);

        titleFld.setEditable(false);

        isbnFld.setEditable(false);

        siggrafeasLbl.setText("Συγγραφέας/Συγγραφείς βιβλίου:");

        scrollerSiggrafeisList.setViewportView(siggrafeisList);

        perigrafiLbl.setText("Περιγραφή βιβλίου:");

        perigrafiTxtPane.setEditable(false);
        scrollerPerigrafiTxtPane.setViewportView(perigrafiTxtPane);

        javax.swing.GroupLayout firstPaneLayout = new javax.swing.GroupLayout(firstPane);
        firstPane.setLayout(firstPaneLayout);
        firstPaneLayout.setHorizontalGroup(
            firstPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(firstPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(firstPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, firstPaneLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(kleisimoParathirouBtn))
                    .addGroup(firstPaneLayout.createSequentialGroup()
                        .addGroup(firstPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(firstPaneLayout.createSequentialGroup()
                                .addGroup(firstPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ekdoseisLbl)
                                    .addComponent(titleLbl)
                                    .addComponent(isbnLbl))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(firstPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(isbnFld)
                                    .addComponent(titleFld)
                                    .addComponent(ekdoseisFld)))
                            .addGroup(firstPaneLayout.createSequentialGroup()
                                .addComponent(siggrafeasLbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(scrollerSiggrafeisList, javax.swing.GroupLayout.DEFAULT_SIZE, 306, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addGroup(firstPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(scrollerPerigrafiTxtPane)
                            .addGroup(firstPaneLayout.createSequentialGroup()
                                .addComponent(perigrafiLbl)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        firstPaneLayout.setVerticalGroup(
            firstPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(firstPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(firstPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(isbnLbl)
                    .addComponent(isbnFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(perigrafiLbl))
                .addGroup(firstPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(firstPaneLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(firstPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(titleLbl)
                            .addComponent(titleFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(firstPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ekdoseisLbl)
                            .addComponent(ekdoseisFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(firstPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(scrollerSiggrafeisList, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(siggrafeasLbl)))
                    .addGroup(firstPaneLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(scrollerPerigrafiTxtPane)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(kleisimoParathirouBtn)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollerBooksTable, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1001, Short.MAX_VALUE)
                    .addComponent(firstPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollerBooksTable, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(firstPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable booksTable;
    private javax.swing.JTextField ekdoseisFld;
    private javax.swing.JLabel ekdoseisLbl;
    private javax.swing.JPanel firstPane;
    private javax.swing.JTextField isbnFld;
    private javax.swing.JLabel isbnLbl;
    private javax.swing.JButton kleisimoParathirouBtn;
    private javax.swing.JLabel perigrafiLbl;
    private javax.swing.JTextPane perigrafiTxtPane;
    private javax.swing.JScrollPane scrollerBooksTable;
    private javax.swing.JScrollPane scrollerPerigrafiTxtPane;
    private javax.swing.JScrollPane scrollerSiggrafeisList;
    private javax.swing.JLabel siggrafeasLbl;
    private javax.swing.JList siggrafeisList;
    private javax.swing.JTextField titleFld;
    private javax.swing.JLabel titleLbl;
    // End of variables declaration//GEN-END:variables
}
