package formes;

import database.connection.DbConnection;
import database.models.IstorikoMelous;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Types;
import java.util.LinkedList;
import javax.swing.JOptionPane;
import table_models.EmfanisiIstorikouTableModel;

public class EmfanisiIstorikouMelousInternalFrame extends javax.swing.JInternalFrame {

    /**
     * Creates new form EmfanisiIstorikouMelousInternalFrame
     */
    public EmfanisiIstorikouMelousInternalFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kleisimoParathirouBtn = new javax.swing.JButton();
        istorikoTableScroller = new javax.swing.JScrollPane();
        istorikoTable = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        amMelousLbl = new javax.swing.JLabel();
        amMelousFld = new javax.swing.JTextField();
        fortwsiBtn = new javax.swing.JButton();
        istorikoLbl = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        synoloAntitypwnPouExeiDaneisteiLbl = new javax.swing.JLabel();
        sinoloAntitypwnPouExeiDaneisteiFld = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Εμφάνιση Ιστορικού Μέλους");

        kleisimoParathirouBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui_icons/close.png"))); // NOI18N
        kleisimoParathirouBtn.setText("Κλείσιμο Παράθυρου");
        kleisimoParathirouBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kleisimoParathirouBtnActionPerformed(evt);
            }
        });

        istorikoTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ISBN", "Αύξων αριθμός αντίτυπου", "ΑΜ Μέλους", "Ημερομηνία Δανεισμού", "Ημερομηνία Επιστροφής"
            }
        ));
        istorikoTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        istorikoTableScroller.setViewportView(istorikoTable);

        amMelousLbl.setText("Δώσε ΑΜ μέλους:");

        fortwsiBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui_icons/search.png"))); // NOI18N
        fortwsiBtn.setText("Φόρτωση");
        fortwsiBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fortwsiBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(amMelousLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(amMelousFld, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(fortwsiBtn)
                .addContainerGap(45, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(amMelousLbl)
                    .addComponent(amMelousFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fortwsiBtn))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        istorikoLbl.setText("Το ιστορικό του μέλους είναι:");

        synoloAntitypwnPouExeiDaneisteiLbl.setText("Σύνολο αντιτύπων που εχει δανειστεί:");

        sinoloAntitypwnPouExeiDaneisteiFld.setEditable(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(synoloAntitypwnPouExeiDaneisteiLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sinoloAntitypwnPouExeiDaneisteiFld, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(synoloAntitypwnPouExeiDaneisteiLbl)
                    .addComponent(sinoloAntitypwnPouExeiDaneisteiFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(kleisimoParathirouBtn))
                    .addComponent(istorikoTableScroller, javax.swing.GroupLayout.DEFAULT_SIZE, 896, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(istorikoLbl)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(istorikoLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(istorikoTableScroller, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(kleisimoParathirouBtn)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void kleisimoParathirouBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kleisimoParathirouBtnActionPerformed
        this.dispose();
    }//GEN-LAST:event_kleisimoParathirouBtnActionPerformed

    private void fortwsiBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fortwsiBtnActionPerformed

        try {
            Integer.parseInt(amMelousFld.getText());
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Δώσε έγκυρο ΑΜ!");
            return;
        }

        if (amMelousFld.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(this, "Δώσε ΑΜ μέλους!");
            return;
        }//if.

        istorikoTable.setModel(new EmfanisiIstorikouTableModel(Integer.parseInt(amMelousFld.getText())));

        LinkedList<IstorikoMelous> istoriko = ((EmfanisiIstorikouTableModel) istorikoTable.getModel()).getData();
        if (istoriko.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Το μέλος με ΑΜ: " + amMelousFld.getText() + " δεν εχει ιστορικό!");
        }

        //=========================================================================
        //klisi ths stored procedure gia na vroume to plithos twn daneismwn pou exei kanei ena melos........
        try {
            Connection con = DbConnection.getInstance().getConnection();
            try (CallableStatement prepareCall = con.prepareCall("{call posaAntitypaExeiDaneisteiEnaMelos(?, ?)}")) {
                prepareCall.setInt(1, Integer.parseInt(amMelousFld.getText()));
                prepareCall.registerOutParameter(2, Types.INTEGER);
                prepareCall.executeQuery();

                int plithosDaneismwn = prepareCall.getInt(2);

                sinoloAntitypwnPouExeiDaneisteiFld.setText(plithosDaneismwn + "");
            }
        } catch (SQLException ex) {
            System.err.println(ex.getMessage());
        }

    }//GEN-LAST:event_fortwsiBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField amMelousFld;
    private javax.swing.JLabel amMelousLbl;
    private javax.swing.JButton fortwsiBtn;
    private javax.swing.JLabel istorikoLbl;
    private javax.swing.JTable istorikoTable;
    private javax.swing.JScrollPane istorikoTableScroller;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton kleisimoParathirouBtn;
    private javax.swing.JTextField sinoloAntitypwnPouExeiDaneisteiFld;
    private javax.swing.JLabel synoloAntitypwnPouExeiDaneisteiLbl;
    // End of variables declaration//GEN-END:variables
}
