package formes;

import database.connection.DbConnection;
import database.daos.AntitypaDAO;
import database.daos.IstorikoMelousDAO;
import database.models.Antitypo;
import database.models.IstorikoMelous;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Types;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import table_models.EmfanisiIstorikouAntitypouTableModel;

public class IstorikoDaneismouAntitypouInternalFrame extends javax.swing.JInternalFrame {

    private final AntitypaDAO antitypaDao = new AntitypaDAO(DbConnection.getInstance().getConnection());
    private final IstorikoMelousDAO istorikoMelousDao = new IstorikoMelousDAO(DbConnection.getInstance().getConnection());

    /**
     * Creates new form IstorikoDaneismouAntitypouInternalFrame
     */
    public IstorikoDaneismouAntitypouInternalFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        firstPane = new javax.swing.JPanel();
        isbnLbl = new javax.swing.JLabel();
        auxwnArithmosLbl = new javax.swing.JLabel();
        isbnFld = new javax.swing.JTextField();
        idFld = new javax.swing.JTextField();
        fortwseBtn = new javax.swing.JButton();
        secondPane = new javax.swing.JPanel();
        posesForesLbl = new javax.swing.JLabel();
        posesForesFld = new javax.swing.JTextField();
        scrollPane = new javax.swing.JScrollPane();
        istorikoAntitypouTable = new javax.swing.JTable();
        kleisimoParathirouBtn = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Ιστορικό Δανεισμού Αντίτυπου");

        isbnLbl.setText("Δώσε ISBN:");

        auxwnArithmosLbl.setText("Δώσε αύξων αριθμό αντίτυπου:");

        fortwseBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui_icons/search.png"))); // NOI18N
        fortwseBtn.setText("Φόρτωσε");
        fortwseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fortwseBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout firstPaneLayout = new javax.swing.GroupLayout(firstPane);
        firstPane.setLayout(firstPaneLayout);
        firstPaneLayout.setHorizontalGroup(
            firstPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(firstPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(firstPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(firstPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(firstPaneLayout.createSequentialGroup()
                            .addComponent(isbnLbl)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(isbnFld, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(firstPaneLayout.createSequentialGroup()
                            .addComponent(auxwnArithmosLbl)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(idFld)))
                    .addComponent(fortwseBtn))
                .addContainerGap(103, Short.MAX_VALUE))
        );
        firstPaneLayout.setVerticalGroup(
            firstPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(firstPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(firstPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(isbnLbl)
                    .addComponent(isbnFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(firstPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(auxwnArithmosLbl)
                    .addComponent(idFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(fortwseBtn)
                .addContainerGap())
        );

        posesForesLbl.setText("Φορές που εχει δανειστεί το αντίτυπο:");

        posesForesFld.setEditable(false);

        javax.swing.GroupLayout secondPaneLayout = new javax.swing.GroupLayout(secondPane);
        secondPane.setLayout(secondPaneLayout);
        secondPaneLayout.setHorizontalGroup(
            secondPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(secondPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(posesForesLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(posesForesFld, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(95, Short.MAX_VALUE))
        );
        secondPaneLayout.setVerticalGroup(
            secondPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(secondPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(secondPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(posesForesLbl)
                    .addComponent(posesForesFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        istorikoAntitypouTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ISBN", "Αύξων αριθμός αντιτύπου", "ΑΜ Δανειζόμενου Μέλους", "Ημερομηνία Δανεισμού", "Ημερομηνία Επιστροφής"
            }
        ));
        scrollPane.setViewportView(istorikoAntitypouTable);

        kleisimoParathirouBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui_icons/close.png"))); // NOI18N
        kleisimoParathirouBtn.setText("Κλείσιμο Παράθυρου");
        kleisimoParathirouBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kleisimoParathirouBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollPane)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(firstPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(secondPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(kleisimoParathirouBtn)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(firstPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(secondPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(scrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(kleisimoParathirouBtn)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void kleisimoParathirouBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kleisimoParathirouBtnActionPerformed
        this.dispose();
    }//GEN-LAST:event_kleisimoParathirouBtnActionPerformed

    private void fortwseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fortwseBtnActionPerformed

        String in_isbn = isbnFld.getText();
        String in_id = idFld.getText();

        //elegxoume ean o xristis simplirwse ta pedia....
        if (in_isbn.trim().equals("") || in_id.trim().equals("")) {
            JOptionPane.showMessageDialog(this, "Παρακαλώ συμπληρώστε τα πεδία!");
            return;
        }//if.

        //elegxos an yparxei antitypo me auto to id kai isbn...
        Antitypo ant = antitypaDao.anaktisiAntitypou(in_isbn, Integer.parseInt(in_id));
        if (ant == null) {
            JOptionPane.showMessageDialog(this, "Δεν υπάρχει αντίτυπο με αυτο το ISBN και τον αύξων αριθμό!");
            return;
        }//if.

        //ean ftasame edw shmainei oti yparxei to antitypo ara fortwnoume to modelo tou....
        istorikoAntitypouTable.setModel(new EmfanisiIstorikouAntitypouTableModel(in_isbn, Integer.parseInt(in_id)));

        //ean to antitypo auto den to exei daneistei kaneis pote tote emfanizoume minima....
        ArrayList<IstorikoMelous> istAnt = ((EmfanisiIstorikouAntitypouTableModel) istorikoAntitypouTable.getModel()).getData();
        if (istAnt.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Το συγκεκριμένο αντίτυπο δεν έχει δανειστεί ποτέ απο κάποιο μέλος!");
            isbnFld.setText("");
            idFld.setText("");
            posesForesFld.setText("");
            istorikoAntitypouTable.setModel(new javax.swing.table.DefaultTableModel(
                    new Object[][]{},
                    new String[]{
                        "ISBN", "Αύξων αριθμός αντιτύπου", "ΑΜ Δανειζόμενου Μέλους", "Ημερομηνία Δανεισμού", "Ημερομηνία Επιστροφής"
                    }
            ));
            return;
        }//if.

        //kaloume th stored function me onoma: posesForesToAntitypo h opoia epistrefei to poses fores ena antitypo exei daneistei apo melh.
        try {
            Connection con = DbConnection.getInstance().getConnection();
            CallableStatement cs = con.prepareCall("{? = call posesForesToAntitypo(?, ?)}");
            int count;
            cs.setString(2, in_isbn);
            cs.setInt(3, Integer.parseInt(in_id));
            cs.registerOutParameter(1, Types.INTEGER);
            cs.execute();
            count = cs.getInt(1);

            posesForesFld.setText(count + "");
        } catch (SQLException | NumberFormatException ex) {
            System.err.println(ex.getMessage());
        }

    }//GEN-LAST:event_fortwseBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel auxwnArithmosLbl;
    private javax.swing.JPanel firstPane;
    private javax.swing.JButton fortwseBtn;
    private javax.swing.JTextField idFld;
    private javax.swing.JTextField isbnFld;
    private javax.swing.JLabel isbnLbl;
    private javax.swing.JTable istorikoAntitypouTable;
    private javax.swing.JButton kleisimoParathirouBtn;
    private javax.swing.JTextField posesForesFld;
    private javax.swing.JLabel posesForesLbl;
    private javax.swing.JScrollPane scrollPane;
    private javax.swing.JPanel secondPane;
    // End of variables declaration//GEN-END:variables
}
