/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package formes;

/**
 *
 * @author nikos
 */
public class NeosDaneismosAntitypouVivliouInternalFrame extends javax.swing.JInternalFrame {

    /**
     * Creates new form NeosDaneismosAntitypouVivliouInternalFrame
     */
    public NeosDaneismosAntitypouVivliouInternalFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPane = new javax.swing.JPanel();
        kleisimoParathirouBtn = new javax.swing.JButton();
        isbnAntitypouBibliouLbl = new javax.swing.JLabel();
        auxwnArithmosAntitypouVivliouLbl = new javax.swing.JLabel();
        arithmosMitrwouMelousLbl = new javax.swing.JLabel();
        isbnAntitypouVivliouFld = new javax.swing.JTextField();
        auxwnArithmosAntitypouVivliouFld = new javax.swing.JTextField();
        arithmosMitrwouMelousFld = new javax.swing.JTextField();
        kataxwrisiDaneismouBtn = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Νέος Δανεισμός Αντίτυπου Βιβλίου");

        kleisimoParathirouBtn.setText("Κλείσιμο Παράθυρου");

        isbnAntitypouBibliouLbl.setText("Δώσε ISBN αντίτυπου βιβλίου:");

        auxwnArithmosAntitypouVivliouLbl.setText("Δώσε αύξων αριθμό αντίτυπου βιβλίου:");

        arithmosMitrwouMelousLbl.setText("Δώσε Αριθμό Μητρώου Μέλους:");

        kataxwrisiDaneismouBtn.setText("Καταχώρηση Δανεισμού");

        javax.swing.GroupLayout mainPaneLayout = new javax.swing.GroupLayout(mainPane);
        mainPane.setLayout(mainPaneLayout);
        mainPaneLayout.setHorizontalGroup(
            mainPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPaneLayout.createSequentialGroup()
                        .addGap(0, 284, Short.MAX_VALUE)
                        .addComponent(kataxwrisiDaneismouBtn)
                        .addGap(18, 18, 18)
                        .addComponent(kleisimoParathirouBtn))
                    .addGroup(mainPaneLayout.createSequentialGroup()
                        .addGroup(mainPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(isbnAntitypouBibliouLbl)
                            .addComponent(auxwnArithmosAntitypouVivliouLbl)
                            .addComponent(arithmosMitrwouMelousLbl))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(mainPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(isbnAntitypouVivliouFld)
                            .addComponent(auxwnArithmosAntitypouVivliouFld)
                            .addComponent(arithmosMitrwouMelousFld, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        mainPaneLayout.setVerticalGroup(
            mainPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(isbnAntitypouBibliouLbl)
                    .addComponent(isbnAntitypouVivliouFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(mainPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(auxwnArithmosAntitypouVivliouLbl)
                    .addComponent(auxwnArithmosAntitypouVivliouFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(mainPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(arithmosMitrwouMelousLbl)
                    .addComponent(arithmosMitrwouMelousFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(mainPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kleisimoParathirouBtn)
                    .addComponent(kataxwrisiDaneismouBtn))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField arithmosMitrwouMelousFld;
    private javax.swing.JLabel arithmosMitrwouMelousLbl;
    private javax.swing.JTextField auxwnArithmosAntitypouVivliouFld;
    private javax.swing.JLabel auxwnArithmosAntitypouVivliouLbl;
    private javax.swing.JLabel isbnAntitypouBibliouLbl;
    private javax.swing.JTextField isbnAntitypouVivliouFld;
    private javax.swing.JButton kataxwrisiDaneismouBtn;
    private javax.swing.JButton kleisimoParathirouBtn;
    private javax.swing.JPanel mainPane;
    // End of variables declaration//GEN-END:variables
}
