package formes;

import database.connection.DbConnection;
import database.daos.VivliothikarioiDAO;
import database.models.Vivliothikarios;
import javax.swing.JOptionPane;

/**
 *
 * @author nikos
 */
public class SindesiStoSistima extends javax.swing.JFrame {

    private final VivliothikarioiDAO vivliothikarioiDAO = new VivliothikarioiDAO(DbConnection.getInstance().getConnection());
    private boolean accessGranted = false;
    private Vivliothikarios sindedemenosVivliothikarios;

    public boolean isAccessGranted() {
        return accessGranted;
    }

    public void setAccessGranted(boolean accessGranted) {
        this.accessGranted = accessGranted;
    }

    /**
     * Creates new form SindesiStoSistima
     */
    public SindesiStoSistima() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPane = new javax.swing.JPanel();
        amLbl = new javax.swing.JLabel();
        passLbl = new javax.swing.JLabel();
        amFld = new javax.swing.JTextField();
        passFld = new javax.swing.JPasswordField();
        ipiresiesLbl = new javax.swing.JLabel();
        kleisimoEfarmogisBtn = new javax.swing.JButton();
        sindesiBtn = new javax.swing.JButton();
        welcomeLbl = new javax.swing.JLabel();
        ipiresiesBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Σύνδεση στο σύστημα βιβλιοθήκης");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        amLbl.setText("Αριθμός μητρώου:");

        passLbl.setText("Κωδικός:");

        ipiresiesLbl.setText("Υπηρεσίες Βιβλιοθήκης:");

        kleisimoEfarmogisBtn.setText("Κλείσιμο εφαρμογής");
        kleisimoEfarmogisBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kleisimoEfarmogisBtnActionPerformed(evt);
            }
        });

        sindesiBtn.setText("Σύνδεση");
        sindesiBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sindesiBtnActionPerformed(evt);
            }
        });

        welcomeLbl.setText("Καλώς ήρθατε! Παρακαλώ συνδεθείτε για να συνεχίσετε.");

        ipiresiesBtn.setText("Υπηρεσίες");
        ipiresiesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ipiresiesBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mainPaneLayout = new javax.swing.GroupLayout(mainPane);
        mainPane.setLayout(mainPaneLayout);
        mainPaneLayout.setHorizontalGroup(
            mainPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPaneLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(sindesiBtn)
                        .addGap(18, 18, 18)
                        .addComponent(kleisimoEfarmogisBtn))
                    .addGroup(mainPaneLayout.createSequentialGroup()
                        .addComponent(welcomeLbl)
                        .addGap(0, 125, Short.MAX_VALUE))
                    .addGroup(mainPaneLayout.createSequentialGroup()
                        .addGroup(mainPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ipiresiesLbl)
                            .addComponent(amLbl)
                            .addComponent(passLbl))
                        .addGap(7, 7, 7)
                        .addGroup(mainPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(amFld)
                            .addComponent(passFld)
                            .addGroup(mainPaneLayout.createSequentialGroup()
                                .addComponent(ipiresiesBtn)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        mainPaneLayout.setVerticalGroup(
            mainPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(welcomeLbl)
                .addGap(18, 18, 18)
                .addGroup(mainPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(amLbl)
                    .addComponent(amFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(mainPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passLbl)
                    .addComponent(passFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(mainPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ipiresiesLbl)
                    .addComponent(ipiresiesBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(mainPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sindesiBtn)
                    .addComponent(kleisimoEfarmogisBtn))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing

        int res = JOptionPane.showConfirmDialog(this, "Είστε σίγουρος?");
        if (res == JOptionPane.YES_OPTION) {
            System.exit(0);
        }

    }//GEN-LAST:event_formWindowClosing

    private void kleisimoEfarmogisBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kleisimoEfarmogisBtnActionPerformed
        System.exit(0);
    }//GEN-LAST:event_kleisimoEfarmogisBtnActionPerformed

    private void sindesiBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sindesiBtnActionPerformed

        try {
            String input = amFld.getText();
            Integer.parseInt(input);
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Παρακαλω εισάγετε σωστό ΑΜ!");
            return;
        }

        if (amFld.getText().trim().equals("") || passFld.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(this, "Παρακαλώ συμπλήρωσε τα πεδία!");
            return;
        }

        Vivliothikarios obj = new Vivliothikarios();
        obj.setAm(Integer.parseInt(amFld.getText()));
        obj.setPassword(passFld.getText());

        obj = vivliothikarioiDAO.egyrosVivliothikarios(obj);
        if (obj != null) {
            accessGranted = true;
            sindedemenosVivliothikarios = obj;
        } else {
            accessGranted = false;
            JOptionPane.showMessageDialog(this, "Άρνηση πρόσβασης!");
        }


    }//GEN-LAST:event_sindesiBtnActionPerformed

    private void ipiresiesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ipiresiesBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ipiresiesBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField amFld;
    private javax.swing.JLabel amLbl;
    private javax.swing.JButton ipiresiesBtn;
    private javax.swing.JLabel ipiresiesLbl;
    private javax.swing.JButton kleisimoEfarmogisBtn;
    private javax.swing.JPanel mainPane;
    private javax.swing.JPasswordField passFld;
    private javax.swing.JLabel passLbl;
    private javax.swing.JButton sindesiBtn;
    private javax.swing.JLabel welcomeLbl;
    // End of variables declaration//GEN-END:variables

    public Vivliothikarios getSindedemenosVivliothikarios() {
        return sindedemenosVivliothikarios;
    }
}
