package formes;

import database.connection.DbConnection;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Types;

public class StatistikaAntitypwnInternalFrame extends javax.swing.JInternalFrame {

    /**
     * Creates new form StatistikaAntitypwnInternalFrame
     */
    public StatistikaAntitypwnInternalFrame() {
        initComponents();
        fortwseStatistikaPeriKatastasisAntitypwn();
    }

    private void fortwseStatistikaPeriKatastasisAntitypwn() {
        Connection conn = DbConnection.getInstance().getConnection();
        try (CallableStatement cs = conn.prepareCall("{call epistrofiPlithousAntitypwnVasiKatastasis(?, ?)}");) {

            //=====kaloume thn stored procedure gia na vroume to plithos antitypwn me kaki katastasi================
            cs.setString(1, "Κακιά");
            cs.registerOutParameter(2, Types.INTEGER);
            cs.executeQuery();
            int plithos_kakis = cs.getInt(2);

            //=====kaloume thn stored procedure gia na vroume to plithos antitypwn se metria katastasi===============
            cs.setString(1, "Μέτρια");
            cs.registerOutParameter(2, Types.INTEGER);
            cs.executeQuery();
            int plithos_metrias = cs.getInt(2);

            //======kaloume thn stored procedure gia na vroume to plithos antitypwn se kali katastasi================
            cs.setString(1, "Καλή");
            cs.registerOutParameter(2, Types.INTEGER);
            cs.executeQuery();
            int plithos_kalis = cs.getInt(2);

            //=====kaloume thn stored procedure gia na vroume to plithos antitypwn se aristh katastasi================
            cs.setString(1, "Άριστη");
            cs.registerOutParameter(2, Types.INTEGER);
            cs.executeQuery();
            int plithos_aristis = cs.getInt(2);

            //======twra vazoume tis plirofories sta text fields====================
            antitypaKakiFld.setText(plithos_kakis + "");
            antitypaMetriaFld.setText(plithos_metrias + "");
            antitypaKaliFld.setText(plithos_kalis + "");
            antitypaAristiFld.setText(plithos_aristis + "");

        } catch (SQLException ex) {
            System.err.println(ex.getMessage());
        }

    }//fortwseStatistikaPeriKatastasisAntitypwn.

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPane = new javax.swing.JPanel();
        statisitkaKatastasisLbl = new javax.swing.JLabel();
        synoloAntitypaKakiLbl = new javax.swing.JLabel();
        antitypaKakiFld = new javax.swing.JTextField();
        synoloAntitypwnMetriaLbl = new javax.swing.JLabel();
        antitypaMetriaFld = new javax.swing.JTextField();
        sinoloAntitypwnKalhLbl = new javax.swing.JLabel();
        antitypaKaliFld = new javax.swing.JTextField();
        synoloAntitypwnAristhLbl = new javax.swing.JLabel();
        antitypaAristiFld = new javax.swing.JTextField();
        kleisimoParathirouBtn = new javax.swing.JButton();
        ananewsiStoixeiwnBtn = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Στατιστικά Αντιτύπων");

        statisitkaKatastasisLbl.setText("Στατιστικά Κατάστασης:");

        synoloAntitypaKakiLbl.setText("Σύνολο αντιτύπων σε κακή κατάσταση:");

        antitypaKakiFld.setEditable(false);

        synoloAntitypwnMetriaLbl.setText("Σύνολο αντιτύπων σε μέτρια κατάσταση:");

        antitypaMetriaFld.setEditable(false);

        sinoloAntitypwnKalhLbl.setText("Σύνολο αντιτύπων σε καλή κατάσταση:");

        antitypaKaliFld.setEditable(false);

        synoloAntitypwnAristhLbl.setText("Σύνολο αντιτύπων σε άριστη κατάσταση:");

        antitypaAristiFld.setEditable(false);

        kleisimoParathirouBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui_icons/close.png"))); // NOI18N
        kleisimoParathirouBtn.setText("Κλείσιμο Παράθυρου");
        kleisimoParathirouBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kleisimoParathirouBtnActionPerformed(evt);
            }
        });

        ananewsiStoixeiwnBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui_icons/refresh.png"))); // NOI18N
        ananewsiStoixeiwnBtn.setText("Ανανέωση στοιχείων");
        ananewsiStoixeiwnBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ananewsiStoixeiwnBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mainPaneLayout = new javax.swing.GroupLayout(mainPane);
        mainPane.setLayout(mainPaneLayout);
        mainPaneLayout.setHorizontalGroup(
            mainPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(statisitkaKatastasisLbl)
                    .addGroup(mainPaneLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(mainPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(synoloAntitypaKakiLbl)
                            .addComponent(synoloAntitypwnMetriaLbl)
                            .addComponent(sinoloAntitypwnKalhLbl)
                            .addComponent(synoloAntitypwnAristhLbl))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(mainPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(antitypaKakiFld)
                            .addComponent(antitypaMetriaFld)
                            .addComponent(antitypaKaliFld)
                            .addComponent(antitypaAristiFld, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPaneLayout.createSequentialGroup()
                .addContainerGap(122, Short.MAX_VALUE)
                .addComponent(ananewsiStoixeiwnBtn)
                .addGap(18, 18, 18)
                .addComponent(kleisimoParathirouBtn)
                .addContainerGap())
        );
        mainPaneLayout.setVerticalGroup(
            mainPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(statisitkaKatastasisLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(synoloAntitypaKakiLbl)
                    .addComponent(antitypaKakiFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(synoloAntitypwnMetriaLbl)
                    .addComponent(antitypaMetriaFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sinoloAntitypwnKalhLbl)
                    .addComponent(antitypaKaliFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(synoloAntitypwnAristhLbl)
                    .addComponent(antitypaAristiFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(mainPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kleisimoParathirouBtn)
                    .addComponent(ananewsiStoixeiwnBtn))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void kleisimoParathirouBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kleisimoParathirouBtnActionPerformed
        this.dispose();
    }//GEN-LAST:event_kleisimoParathirouBtnActionPerformed

    private void ananewsiStoixeiwnBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ananewsiStoixeiwnBtnActionPerformed
        fortwseStatistikaPeriKatastasisAntitypwn();
    }//GEN-LAST:event_ananewsiStoixeiwnBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ananewsiStoixeiwnBtn;
    private javax.swing.JTextField antitypaAristiFld;
    private javax.swing.JTextField antitypaKakiFld;
    private javax.swing.JTextField antitypaKaliFld;
    private javax.swing.JTextField antitypaMetriaFld;
    private javax.swing.JButton kleisimoParathirouBtn;
    private javax.swing.JPanel mainPane;
    private javax.swing.JLabel sinoloAntitypwnKalhLbl;
    private javax.swing.JLabel statisitkaKatastasisLbl;
    private javax.swing.JLabel synoloAntitypaKakiLbl;
    private javax.swing.JLabel synoloAntitypwnAristhLbl;
    private javax.swing.JLabel synoloAntitypwnMetriaLbl;
    // End of variables declaration//GEN-END:variables
}
